### ISSUE TITLE
Advanced Search Form Meta Issue (from 1171)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#14]
**Problem Description:**
This issue will act as a way of keeping track of all issues specific to the advanced search form.

**Requirements:** 
https://app.smartsheet.com/sheets/HhQC82P9vXGM5pXj96824Hq6ggH385RW2635G6q1?view=grid

### Open: 
- [ ] https://github.com/project-lux/lux-frontend/issues/47
- [ ] https://github.com/project-lux/lux-frontend/issues/58
- [x] https://github.com/project-lux/lux-frontend/issues/60
- [x] https://github.com/project-lux/lux-frontend/issues/82
- [ ]  https://github.com/project-lux/lux-marklogic/issues/35
- [ ] https://github.com/project-lux/lux-marklogic/issues/74
- [ ] https://github.com/project-lux/lux-marklogic/issues/49
- [ ] https://github.com/project-lux/lux-frontend/issues/22
- [x] https://github.com/project-lux/lux-frontend/issues/141
- [x] https://github.com/project-lux/lux-frontend/issues/151

**Blocked:** 
- [ ] https://github.com/project-lux/lux-frontend/issues/54 (blocked) 
- [ ] https://github.com/project-lux/lux-frontend/issues/48 (blocked) 
- [ ] https://github.com/project-lux/lux-frontend/issues/29 (blocked) 

**Proposed Improvements:** 
- [ ] https://www.bugherd.com/projects/284041/tasks/2057 (improve search editing)
- [ ] https://www.bugherd.com/projects/284041/tasks/2071 (sentence structure)
- [ ] https://www.bugherd.com/projects/284041/tasks/2072 (contextual help)
- [ ] https://www.bugherd.com/projects/284041/tasks/2047 (layout)
- [ ] https://www.bugherd.com/projects/284041/tasks/2074 (layout)
- [ ] https://www.bugherd.com/projects/284041/tasks/2070 (clarity needed)

**Future Work:** 
- [ ] https://github.com/project-lux/lux-frontend/issues/16
- [ ] https://github.com/project-lux/lux-frontend/issues/17
- [ ] https://github.com/project-lux/lux-frontend/issues/31
- [x] https://github.com/project-lux/lux-frontend/issues/110
- [ ] https://github.com/project-lux/lux-frontend/issues/136 (dupe of 110) 
- [ ] https://github.com/project-lux/lux-marklogic/issues/5

### **Closed:** 
- [x] https://github.com/project-lux/lux-frontend/issues/50
- [x] https://github.com/project-lux/lux-frontend/issues/63
- [x] https://github.com/project-lux/lux-frontend/issues/65
- https://git.yale.edu/lux-its/lux-web/issues/1141
- https://git.yale.edu/lux-its/lux-web/issues/1172
- https://git.yale.edu/lux-its/lux-web/issues/1173
- https://git.yale.edu/lux-its/lux-web/issues/1174
- https://git.yale.edu/lux-its/lux-web/issues/1175
- https://git.yale.edu/lux-its/lux-web/issues/1209
- https://git.yale.edu/lux-its/lux-web/issues/1210
- https://git.yale.edu/lux-its/lux-web/issues/1211
- https://git.yale.edu/lux-its/lux-web/issues/1212
- https://git.yale.edu/lux-its/lux-web/issues/1213
- https://git.yale.edu/lux-its/lux-web/issues/1214
- https://git.yale.edu/lux-its/lux-web/issues/1215
- https://git.yale.edu/lux-its/lux-web/issues/1216
- https://git.yale.edu/lux-its/lux-web/issues/1217
- https://git.yale.edu/lux-its/lux-web/issues/1218
- https://git.yale.edu/lux-its/lux-web/issues/1219
- https://git.yale.edu/lux-its/lux-web/issues/1220
- https://git.yale.edu/lux-its/lux-web/issues/1221
- https://git.yale.edu/lux-its/lux-web/issues/1222
- https://git.yale.edu/lux-its/lux-web/issues/1223
- https://git.yale.edu/lux-its/lux-web/issues/1224
- https://git.yale.edu/lux-its/lux-web/issues/1225
- https://git.yale.edu/lux-its/lux-web/issues/1226
- https://git.yale.edu/lux-its/lux-web/issues/1227
- https://git.yale.edu/lux-its/lux-web/issues/1801
- Note UAT comments on https://git.yale.edu/lux-its/marklogic/issues/1097
- https://github.com/project-lux/lux-frontend/issues/63 (dupe) 

### **Related Links:** 
Bugherd's
- https://www.bugherd.com/projects/284041/tasks/1840
- location in [LUX](https://lux-front-tst.collections.yale.edu/view/results/concepts?q=%7B%22influencedByEvent%22%3A%7B%22name%22%3A%22dynasty%22%7D%7D)
- https://www.bugherd.com/projects/284041/tasks/1885
- location in [LUX](https://lux-front-sbx.collections.yale.edu/view/results/objects?q=%7B%22_scope%22%3A%22item%22%2C%22OR%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F4a172143-a50e-4d91-a88b-a9931bceecf1%22%7D%7D%2C%7B%22material%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F4a172143-a50e-4d91-a88b-a9931bceecf1%22%7D%7D%5D%7D&openSearch=false)

**Comment by roamye** [comment]
propose close as this ticket contains closed issues from the private repo. A new ticket number has been made with AS FE issues: https://github.com/project-lux/lux-frontend/issues/213

**Comment by prowns** [comment]
ok to close
