### ISSUE TITLE
META: Updating Responsible Units/Collection names

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#153]
**Problem Description:**
In LUX we have four Campus Divisions: Yale University Library (YUL), Yale Peabody Museum, (YPM), Yale University Art Gallery (YUAG), Yale Center for British Art (YCBA). This raised an issue as there are some categories which could not be found within these Campus Divisions/Collections.  For example, Elizabeth Club is not a collection but not a campus division. A user does not have the ability to filter on the Elizabeth Club and instead has to filter between one of the four Campus Divisions, which may or may not show results of the Elizabeth Club collection. 

 Since we are rebranding Campus Divisions to Responsibility Units (See issue FE-132) we will now expand to include such categories as Elizabeth club (and others) and their collections to allow users to better refine their searches.  

This issue will serve as a meta ticket for all the work needed to include the new responsible units/collections.

**Expected Behavior/Solution:**
Add additional Responsible Units such as: Paul Mellon Centre, Yale School of Music, Elizabeth Club, Yale Campus Art, and Institute for the Preservation of Cultural Heritage 

Add additional collections such as: Library Collection, Archives, Photo Collection Collection of Musical Instruments, Elizabethan Club Collection, Campus Art Collection any other collection needed. 

**Requirements:**
The following Responsible Units/Collections will be added to Responsible Unit and Collection Facets:

Paul Mellon Centre (UK)
- [x] -  Library Collection, Paul Mellon Centre (UK)
- [x] -  Archives, Paul Mellon Centre (UK)
- [x] -  Photo Collection, Paul Mellon Centre (UK)

Yale School of Music
- [x] -  Morris Steinert Collection of Musical Instruments, Yale School of Music

Elizabethan Club of Yale University 
- [x] -  Elizabethan Club Collection, Yale University

Yale Campus Art
- [x] -  Campus Art Collection, Yale University

Institute for the Preservation of Cultural Heritage
- [ ] - TBD

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
Object Sun Results (TST): 
https://lux-front-tst.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22sun%22%2C%22_lang%22%3A%22en%22%7D&sq=sun

**Dependencies/Blocks:**
- Blocked By: units making their data available. 

**Related Github Issues:**
- Front End: https://github.com/project-lux/lux-frontend/issues/132
- ML: https://github.com/project-lux/lux-marklogic/issues/68

**Related links:**
- BugHerd: https://www.bugherd.com/projects/284041/tasks/1977?text=elizab

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by clarkepeterf** [comment]
@kamerynB  I have updated ML in DEV such that it can support this ticket

**Comment by roamye** [comment]
Awaiting decision on a name for The Institute for Preservation of Cultural Heritage. 

@prowns will meet with them today and confirm/have an update.

**Comment by prowns** [comment]
proposed close. Believe this to be complete.

**Comment by roamye** [comment]
Closing as this is finished. (UAT 8/7)
