### ISSUE TITLE
META: Research on how to Show Similar Objects, Works, People and Groups on their respective record pages. 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#210]
**Problem Description:**
LUX would like to add a feature on records pages such as Objects, Works, and People and Groups where each page will show similar <scope> results for that record. However, we are unsure of what is defined as "similar" for each scope. 

This ticket serves as a meta and research issue for all "show similar <scope>" FE, ML and future MT tickets. 

**Expected Behavior/Solution:**
Define the criteria "similar". What should it include for the show Similar Works on Work Pages, Similar Objects on Object Pages, and Similar People and Group on People and group pages?

Example sites:

- https://collections.mfa.org/objects/38909/chestonchest?ctx=557802af-c04a-4b65-bcb9-127c9a3216c4&idx=1
- https://philamuseum.org/collection/object/89219
- https://dma.org/art/collection (probably just a tag)

**Requirements:**
Define "similar" criteria for: 
- [ ] Similar Works on Work Pages
- [ ] Similar Objects on Object Pages
- [ ] Similar People and Group on People and group pages

Other req: 
- [ ] Define how the UI will appear for "show similar" on record pages. 
- [ ] Indicate to users how a "show similar" result is shown.
- [ ] Decide how results with images/no images will be shown.

Req (after above is completed) 
- [ ] Update existing FE/ML ticket with information found.
- [ ] Create MT ticket for each scope. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Interactions/Advocates discussion
- [ ] Feasibility/Team discussion - Sarah
- [ ] Middle Tier - TBD
- [ ] https://github.com/project-lux/lux-frontend/issues/3
- [ ] https://github.com/project-lux/lux-marklogic/issues/18
- [ ] https://github.com/project-lux/lux-frontend/issues/5
- [ ] https://github.com/project-lux/lux-marklogic/issues/17
- [ ] https://github.com/project-lux/lux-frontend/issues/202
- [ ] https://github.com/project-lux/lux-marklogic/issues/122
- [ ] Questions
- What defines "similar"? What are the requirements for similar search? 
- What are the requirements for the UI? 
- What do we do with results with images/no images? 
- Can we indicate to users how "similar" is shown/selected?

**UAT/LUX Examples:**
- Listed within FE Issues

**Dependencies/Blocks:**
Blocking: 
- https://github.com/project-lux/lux-frontend/issues/3
- https://github.com/project-lux/lux-marklogic/issues/18
- https://github.com/project-lux/lux-frontend/issues/5
- https://github.com/project-lux/lux-marklogic/issues/17
- https://github.com/project-lux/lux-frontend/issues/202
- https://github.com/project-lux/lux-marklogic/issues/122

**Related Github Issues:**

**Related links:**
- These links can consist of resources, bugherds, etc.

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by prowns** [comment]
Discussed at 10/30 ticket forming (Teams discussion from 4/26/24) - interest from @clarkepeterf and @kkdavis14 to work on this. It seems ready to go from ML perpsective.   Discussed at Interactions in May.

**Comment by prowns** [comment]
Notes from 12/6/24 ITS team mtg:

For reference:
- [2024-12-04: Similar Requirements and Planning](https://docs.google.com/document/d/1P0muJ2v1bq-LSNNyLDD2KkZF1LvaSXH7GqSkk4VuBy8/edit?tab=t.0) 
- [Ideal Similars/More Examples](https://docs.google.com/document/d/1yYHzLQI5evtODMy45-LusNl8YDwy4AuFfzflG8PYK2I/edit?tab=t.0#heading=h.nkstjqc355kk) - from Kelly.

Could assign weights to better guage similarity (in this order)
- occupation/role 
- Professional activity type
- Keywords
- nationality,
- gender,
- memberOf
- prof active place
- birth dates
- prof active dates
- death dates
- death place
- birth place (worst)

Some of these will need new search terms.  Will be useful for facets/adv. Search

Should similar be limited to people with at least one of the criteria?  Yes. Can the similar query only query this smaller set (some match)? Yes, it should.  This will make the total number of returned similar records more useful.

Similar - some number of people will have no criteria for assessing similarity How are these handled/treated?
- A similar search on a Person with no criteria returns more People with no criteria: [LUX: Yale Collections Discovery](https://lux-front-tst.collections.yale.edu/view/results/people?q=%7B%22_scope%22%3A%22agent%22%2C%22similar%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fperson%2F15a9c9b8-20d1-4b07-8687-404412aa06ef%22%2C%22_include%22%3A%5B%22keyword%22%2C%22concept%22%2C%22agent%22%2C%22time%22%5D%7D)
- The similar component should not show if there are NO similar results

Next steps
- How to move from research to deployment?
- Peter determining criteria for keywords (e.g warhol/names)  Good for groups but not people

**Comment by roamye** [comment]
12/16 - Core team has decided to pause this work in favor of other priorities(My Collections, Advanced Search, and Unit Portals). All `Similar` tasks have been moved to Future Work.
