### ISSUE TITLE
META: Advanced Search Issues in FE

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#213]
**Problem Description:**
This ticket serves to keep track of all advanced search FE issues. 

To view all FE issues in other repo's please view the project board of issues with the AS label: https://github.com/orgs/project-lux/projects/1/views/11?filterQuery=is%3Aopen+-status%3A%22Future+Work%22%2CDone++label%3A%22Advanced+Search%22

**Solution/Proposal:**

### **Related Issues:**
**Open**
- [ ] https://github.com/project-lux/lux-frontend/issues/47
- [ ] https://github.com/project-lux/lux-frontend/issues/58
- [ ] https://github.com/project-lux/lux-frontend/issues/22

**Blocked**
- [ ] https://github.com/project-lux/lux-frontend/issues/54 (blocked) 
- [ ] https://github.com/project-lux/lux-frontend/issues/48 (blocked) 
- [ ] https://github.com/project-lux/lux-frontend/issues/29 (blocked) 

**Proposed Improvements**
- [ ] https://www.bugherd.com/projects/284041/tasks/2057 (improve search editing)
- [ ] https://www.bugherd.com/projects/284041/tasks/2071 (sentence structure)
- [ ] https://www.bugherd.com/projects/284041/tasks/2072 (contextual help)
- [ ] https://www.bugherd.com/projects/284041/tasks/2047 (layout)
- [ ] https://www.bugherd.com/projects/284041/tasks/2074 (layout)
- [ ] https://www.bugherd.com/projects/284041/tasks/2070 (clarity needed)

**Future Work**
- [ ] https://github.com/project-lux/lux-frontend/issues/16
- [ ] https://github.com/project-lux/lux-frontend/issues/17
- [ ] https://github.com/project-lux/lux-frontend/issues/31

**Comment by kamerynB** [comment]
@roamye Can this issue be moved out of Forming?

**Comment by roamye** [comment]
@kamerynB - yes, I have moved it to prioritization review as it lists all the issues above. 

Thank you for reaching out about it.

**Comment by roamye** [comment]
@prowns - has been updated to include all the other issues with the `redesign` label.

**Comment by roamye** [comment]
Proposal to make the Advanced Search Redesign issues a milestone for the 04/07 or 04/21 deployment. Currently there are a five issues still in forming or may need research. 

Let me know your thoughts. 
@kamerynB @prowns

**Comment by prowns** [comment]
@roamye - blocked pending POW work; please do not schedule yet.

**Comment by roamye** [comment]
@kamerynB - updated. I kept the bugherd under proposed improvements since we have not made a FE ticket for it yet. It is for the future, but unsure if we want the ticket now or later.
