### ISSUE TITLE
Allow Google crawler on select paths (from 1687)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#24]
### Problem Description
Currently robots.txt for LUX advises search bots not to crawl the site at all, since crawlers caused such load for the backend as to bring the whole system to its knees. We'd like to allow Google to crawl LUX item records only and see how it goes.

### Expected Behavior/Solution
- It should allow Google to crawl LUX item record views only: it should not traverse any data or search links.
- LUX should provide schema.org data for Google search results to show rich information

### Requirements 
~- [ ] Document backout plan if google crawl cause performance issues again - https://git.yale.edu/lux-its/lux-web/issues/1687#issuecomment-24116~
- [x] Provide documentation on how to block specific IP address (https://yaleits.atlassian.net/wiki/spaces/DAT/pages/4237983832/Recovery+from+Backend+Crash)
- [x] How should performance should be tested?  Does QA have a crawler tool?   No, there is no test.  
- robots.txt: https://github.com/project-lux/lux-frontend/issues/24#issuecomment-2095982721

### Needed for Promotion
*If an item on the list is not needed, it should be crossed off but not removed.*

- [x] Wireframe/Mockup - Heather - not needed
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
~- [ ] Backend requirements - TBD~
~- [ ] Frontend requirements- TBD~
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

### UAT/LUX Examples ###
*Example endpoints from LUX to use for development and testing, if applicable.*

### Dependencies/Blocks ###
- Blocked By: 
  - [x] https://git.yale.edu/lux-its/lux-project/issues/56 - resolved
  - [x] https://git.yale.edu/lux-its/lux-project/issues/55 <- not required, but still good to do - Firewall to block specific IPs
  - - [x] Manual process - create a ACL list and associate with the firewall that is already in place. Developer will need to read the logs and add the IPs to the blocked list. - Covered by https://git.yale.edu/lux-its/lux-project/issues/55
  - [x] https://github.com/project-lux/lux-frontend/issues/61 <- No Index metatag - Does NOT prevent crawling, just prevents indexing
  - [ ] https://git.yale.edu/lux-its/lux-project/issues/57 <-load testing - not required for release, but still good to do
  - [x] https://github.com/project-lux/lux-frontend/issues/72
  - [x] Google crawler won't pick up dynamic contents - https://git.yale.edu/lux-its/lux-web/issues/1687#issuecomment-25251

**Comment by gigamorph** [comment]
I gave Vincent permission to view our Google Search Console. He couldn't find any problems in the settings either, and also suspected it may be the "reputation" problem. I suggest we try allowing Google bots on our production site with the more restrictive robots.txt rules we've been using in the test site.

**Comment by gigamorph** [comment]
Enabled and inspected access logs for the test site. There have indeed  been requests from Google bots for the pages that were linked from the submitted ones, so at least the crawler is following those links. 

So the question is whether/when they get indexed. From this week, a couple of such pages appeared from searching, which is promising. But there are many more that are supposed to turn up, too. Maybe the process is very slow. Maybe "reputation" is playing a role here. 

The Google search console is not showing those couple in the "indexed pages" list though.

**Comment by gigamorph** [comment]
Vincent had also suggested using sitemap. Although I don't think sitemap fits our need, it may be worth trying with a sample of URLs.

**Comment by jffcamp** [comment]
@gigamorph, based on the decision made at the last team meeting (April 26), we will be allowing this change to proceed to PRD with this release. I'm updating the milestone and status.

Please identify the backout plan in the opening block, even if it is to push an update to robots.txt to again disallow crawling and wait.

**Comment by jffcamp** [comment]
Sorry for the whiplash in status :) - moving back to prioritization review.
Please check the dependency tickets and, if they are still needed, keep them linked. If they aren't needed, remove them.
Thanks very much @gigamorph

**Comment by azaroth42** [comment]
Not ready without documentation. Docs?

**Comment by jffcamp** [comment]
Documentation being added here: https://yaleits.atlassian.net/wiki/spaces/DAT/pages/4237983832/Recovery+from+Backend+Crash

**Comment by gigamorph** [comment]
Revised robots.txt:
```
User-agent: Twitterbot
Disallow:

User-agent: Googlebot
Disallow: /view/results/

User-agent: *
Disallow: /
```

**Comment by jffcamp** [comment]
Untestable from a UAT perspective

Outlook<https://aka.ms/qtex0l> on a phone
________________________________

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Completed.
