### ISSUE TITLE
META: Optimization of LUX for Mobile Devices

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#269]
**Problem Description:**
 In the last 30 days site improve has shown ~23 percent of our users are on LUX mobile devices ([see here](https://my2.siteimprove.com/Analytics/359298/LastThirtyDays/Users/Devices?TabSelect=Devices.DevicesGraph)). 
Mobile usage has gone up in the last two weeks as we have implemented google search, which is expected. 

This ticket serves to discuss the optimization of LUX for mobile devices and monitor the trend of growing mobile users. 

Note: Site Improve uses screen dimensions to categorize a users device status. 
https://help.siteimprove.com/support/solutions/articles/80000447954-definition-of-devices-in-analytics 

**Expected Behavior/Solution:**
Implement POW designs as provided.  

**Requirements:**
POW design files. Kam may update with separate tickets to do this work.  Will be assigned same priority as this ticket. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.
- ~[ ] Wireframe/Mockup - Mike~
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements- TBD
- [x] Are new regression tests required for QA - Amy
- no mobile testing is done
- [x] Questions
- How to handle visualizations?  EXCLUDE
- How to handle Adv. search? EXCLUDE
- What is else is excluded from mobile now? - above
- Does anything currently break on mobile (none reported)
- Do we need a new packet of mobile friendly designs from POW? - YES, linked below

**UAT/LUX Examples:**

**- Example endpoints from LUX to use for development and testing, if applicable.**

**Dependencies/Blocks:**

- None

**Related Github Issues:**
Child tickets: 

- [x] https://github.com/project-lux/lux-frontend/issues/434
- [x] https://github.com/project-lux/lux-frontend/issues/435
- [x]  https://github.com/project-lux/lux-frontend/issues/436
- [x] https://github.com/project-lux/lux-frontend/issues/437
- [x] https://github.com/project-lux/lux-frontend/issues/438
- [x] https://github.com/project-lux/lux-frontend/issues/440
- [x] https://github.com/project-lux/lux-frontend/issues/441
- [x] https://github.com/project-lux/lux-frontend/issues/442
- [x] https://github.com/project-lux/lux-frontend/issues/443
- [x]  https://github.com/project-lux/lux-frontend/issues/525
- [ ]  https://github.com/project-lux/lux-frontend/issues/526
- [x]  https://github.com/project-lux/lux-frontend/issues/527

**Related links:**
- [Devices by Users](https://my2.siteimprove.com/Analytics/359298/LastThirtyDays/Users/Devices?TabSelect=Devices.DevicesPie)
- [Operating systems by Users](https://my2.siteimprove.com/Analytics/359298/LastThirtyDays/Users/OperatingSystems?TabSelect=OperatingSystems.OperatingSystemsChart)
- [Browsers by users](https://my2.siteimprove.com/Analytics/359298/LastThirtyDays/Users/Browsers?TabSelect=Browsers.BrowserChart)
- [Google Search Console Device report](https://search.google.com/search-console/performance/search-analytics?resource_id=https%3A%2F%2Flux.collections.yale.edu%2F&hl=en&breakdown=device)
- [7/8 Mobile Heuristic Evaluation](https://drive.google.com/file/d/1rbtNerMmnYAuQJHDJzMoCc34dBn0f5Ki/view?usp=drive_link)
- POW Updated as of 9/9/24: 
[Presentation](https://www.figma.com/proto/bWS2orxFECNrG92HfG48BL/LUX-Yale-Design-Walkthrough?page-id=3377%3A9485&node-id=3377-9572&viewport=4999%2C493%2C0.26&t=Axk0QSGESY3qeZh1-1&scaling=scale-down&content-scaling=fixed)
[Design walkthrough](https://www.figma.com/design/bWS2orxFECNrG92HfG48BL/LUX-Yale-Design-Walkthrough?node-id=30-6364&node-type=canvas&t=Sy4U7OxDEOrthtNY-0) 
[Prototype](https://www.figma.com/proto/bWS2orxFECNrG92HfG48BL/LUX-Yale-Design-Walkthrough?page-id=182%3A6364&node-id=3317-20738&viewport=-5411%2C-5010%2C0.36&t=yi4XGHaZfpsKRsqT-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3317%3A20738&show-proto-sidebar=1)

**Wireframe/Mockup:**
[Current wireframe from POW - option 1B](https://www.figma.com/proto/72D1OO4ROKGe4nUzIW3Nnu/LUX-Yale-UI?node-id=398-5594&t=3CwjEpAYIHJBVok1-1&scaling=min-zoom&content-scaling=fixed&page-id=182%3A6364&starting-point-node-id=398%3A5594&show-proto-sidebar=1)

**Comment by kamerynB** [comment]
@roamye This is still waiting a decision on the mobile designs correct?

**Comment by roamye** [comment]
@kamerynB - Yes

I spoke to @jffcamp and he recently received something from Jimmy today. So we may have a update sometime this week on whether the consensus is to move forward with 1B or if others still need to review.

**Comment by jffcamp** [comment]
The design will be 1B.
I've requested that POW provide an additional wireframe with a more compact results list. Limiting the data in the list to this:
Objects, please list: 

>  Title
>  Produced by
>  Categorized As – first followed by … if more than one

Works, please list:

> Title
> Creator
> Categorized As – first followed by … if more than one

People & Groups - please list:

> Name
> Occupations – first followed by … if more than one
> Nationalities – first followed by … if more than one

Places - please list:

> Name
> Categorized As – first followed by … if more than one
> Place Hierarchy – Please list the first two, followed by …, then the last two

Concepts - please list

> Name
> Descriptions – first two lines ending with …
> Concept hierarchy - … followed by the last two entries

Events - please list:

> Name
> Categorized As – first followed by … if more than one
> Took Place At

**Comment by kamerynB** [comment]
I believe this will have to be broken out into several smaller issues and this will be the meta ticket for it. @roamye @prowns

**Comment by roamye** [comment]
UAT 8/7: 

Need to validate with interactions. There are some records with the same name and different identifiers. A user would not be able to differentiate by the title or the Name/Categorized As/Place Hierarchy/etc. However, this is a design exercise to see what it would look like. (Compressing the result cards information)

**Comment by roamye** [comment]
@kamerynB - as of 9/9 the following links contain the finalized version for the mobile/desktop updates: 
[Presentation](https://www.figma.com/proto/bWS2orxFECNrG92HfG48BL/LUX-Yale-Design-Walkthrough?page-id=3377%3A9485&node-id=3377-9572&viewport=4999%2C493%2C0.26&t=Axk0QSGESY3qeZh1-1&scaling=scale-down&content-scaling=fixed)
[Design walkthrough](https://www.figma.com/design/bWS2orxFECNrG92HfG48BL/LUX-Yale-Design-Walkthrough?node-id=30-6364&node-type=canvas&t=Sy4U7OxDEOrthtNY-0) 
[Prototype](https://www.figma.com/proto/bWS2orxFECNrG92HfG48BL/LUX-Yale-Design-Walkthrough?page-id=182%3A6364&node-id=3317-20738&viewport=-5411%2C-5010%2C0.36&t=yi4XGHaZfpsKRsqT-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3317%3A20738&show-proto-sidebar=1)

I have also linked these in the related links section of this issue. Would a PDF copy of the finalized figmas be helpful? 

If you would like, I can create some initial requirements based on what I have seen in the figma. We can then map out tickets based on what is needed. 

Please let me know if you have any questions, or would like my help mapping out the issues. 

Thank you!

**Comment by roamye** [comment]
Ticket forming 9/18: 
- @kamerynB to look at the links. This issue is to be looked at first before #269.

**Comment by kamerynB** [comment]
@roamye @jffcamp @prowns I had a chance to go through the docs listed [in Amy's comment here](https://github.com/project-lux/lux-frontend/issues/269#issuecomment-2339042121). I had a few questions and comments but overall I really like these layouts and styling. I will have to go through these again and start writing out specifics of what the frontend needs to change. 

1. The `Sort By` button on results pages does not separate the sorting direction vs the sorting field. Unless we wish to change this functionality, those two options should be separate.
2. This is something that I've been aware of for some time, but does it make sense to have the About section for each entity page appear above any relationships listed? I know there may be exceptions to this but I wanted to ask. 
3. Should the feedback button always be below the Data Sources, even on desktops? The mobile designs have it below the Data Sources and I kind of like that since all the data grouped together and then a user can say "oh look, feedback button".
4. I like the tabs to dropdowns when going from desktop to mobile on entity pages HOWEVER (see number 5)
5. It took me a second to realize the content below the dropdowns was related to the dropdown. A layout similar to the results page dropdown would make more sense and be consistent across all pages. I've included screenshots below of what I am thinking.
6. Will the IIIF rights description always be a modal that pops up in front of the IIIF viewer?


#5 Example:
What is shown:
![Image](https://github.com/user-attachments/assets/ebb8ddf6-8fb5-468c-ab9f-ac96cd268845)

What I was thinking:
![Image](https://github.com/user-attachments/assets/6084b752-3a0b-4318-a777-12e88be168ba)

**Comment by roamye** [comment]
Helpful links for Kams comment above. 
1. [Example of Sort By and Sort Direction as one button rather than two](https://www.figma.com/proto/bWS2orxFECNrG92HfG48BL/LUX-Yale-Design-Walkthrough?page-id=182%3A6364&node-id=1004-23124&viewport=-5411%2C-5010%2C0.36&t=yi4XGHaZfpsKRsqT-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1004%3A23124&show-proto-sidebar=1)
2. I am unsure which figma links shows this. I reviewed all them and the relationship (if any) is shown above the about section, for example: [Mobile - Places](https://www.figma.com/proto/bWS2orxFECNrG92HfG48BL/LUX-Yale-Design-Walkthrough?page-id=182%3A6364&node-id=803-7357&viewport=-5411%2C-5010%2C0.36&t=yi4XGHaZfpsKRsqT-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=803%3A7357&show-proto-sidebar=1) and  [Mobile People & Groups](https://www.figma.com/proto/bWS2orxFECNrG92HfG48BL/LUX-Yale-Design-Walkthrough?page-id=182%3A6364&node-id=1152-10519&viewport=-5411%2C-5010%2C0.36&t=yi4XGHaZfpsKRsqT-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1152%3A10519&show-proto-sidebar=1). Is there a link you can provide that lists the about section above the relationships? 
3. Example of feedback button for [mobile ](https://www.figma.com/proto/bWS2orxFECNrG92HfG48BL/LUX-Yale-Design-Walkthrough?page-id=182%3A6364&node-id=803-7357&viewport=-5411%2C-5010%2C0.36&t=yi4XGHaZfpsKRsqT-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=803%3A7357&show-proto-sidebar=1) vs [desktop](https://lux.collections.yale.edu/view/place/c7723bdd-598e-458f-8e1c-4ee6b17e6c22)
4.  [entity tabs](https://www.figma.com/proto/bWS2orxFECNrG92HfG48BL/LUX-Yale-Design-Walkthrough?page-id=182%3A6364&node-id=803-7357&viewport=-5411%2C-5010%2C0.36&t=yi4XGHaZfpsKRsqT-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=803%3A7357&show-proto-sidebar=1) vs [tabs ](https://www.figma.com/proto/bWS2orxFECNrG92HfG48BL/LUX-Yale-Design-Walkthrough?page-id=182%3A6364&node-id=1718-41825&viewport=-5411%2C-5010%2C0.36&t=yi4XGHaZfpsKRsqT-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1718%3A41825&show-proto-sidebar=1)
5. see above links.
6. [Rights description that was chosen](https://www.figma.com/proto/bWS2orxFECNrG92HfG48BL/LUX-Yale-Design-Walkthrough?page-id=182%3A6364&node-id=1122-12806&viewport=-5411%2C-5010%2C0.36&t=yi4XGHaZfpsKRsqT-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1122%3A12806&show-proto-sidebar=1) vs [current desktop ](https://lux.collections.yale.edu/view/visual/c35629f2-b067-40e6-8606-81eb45688837)

Comments: 
1.  I believe the sort by and sort direction are listed separately upon selecting the Sort & Refine button. I am not certain in this as I could not find a figma link that shows how button is displayed once selected. If it is how I believe it is, then this may not be an issue. @jffcamp & @prowns - can we ask Jimmy if there was a mockup for this? or confirm if this is how it functions? 
2. Please see above. I was unsure where it was showing the about section about the relationships in entity pages. 
3. I think this is a good idea. It is also would put the feedback button closer to the contact button on the desktop which could be useful for users. 
4. I cannot remember why there is difference between the results tabs vs entity tabs. At one point, (i'm 99% certain) the original results tabs looked like the current entity tabs. ([see here for example](https://drive.google.com/file/d/1rbtNerMmnYAuQJHDJzMoCc34dBn0f5Ki/view))  It was then decided to not have these tabs separated so I agree that the entity tabs should also not be separated. They should both have the same layout as you listed in your mockup. 
5. See comment above. (4) 
6. I believe it should be. The current desktop also has it pop up but because the layout is different it shows at the bottom left corner rather than in the middle of the image.

**Comment by roamye** [comment]
From UX/BA Meeting 9/25: 
1. @prowns will reach out to Jimmy to see if there is a figma link for what the `Sort & Refine` button looks like when selected. More discussion can be had afterwards. 
2. No discussion was had as it was unclear where the about section was above the relationships on entity pages. 
3. The mobile feedback button was not supposed to be at the bottom, it should be above the `Data Sources` as it is now in desktop. 
4. From a UX perspective those tabs should match the same layout as the Object/Works/etc tabs so it shows a connection from the tab to the results. 
5. See comment above (4) 
6. Rights description opening in the middle could be an accessibility issues. I will reach out to Kara to follow up on this.

**Comment by kamerynB** [comment]
@roamye Thank you. I will await further decisions/discussions. 😁

**Comment by roamye** [comment]
11/4 discussion with Kam: 
will probably need a ticket for each of the below: 
- result page (1) 
- two entity page types (concepts and works) and people/event/etc have their own types of pages. (7?)

**Comment by kamerynB** [comment]
1. This appears to be fixed in the [figma files](https://www.figma.com/proto/bWS2orxFECNrG92HfG48BL/LUX-Yale-Design-Walkthrough?page-id=182%3A6364&node-id=3591-9971&viewport=-5411%2C-5010%2C0.36&t=yi4XGHaZfpsKRsqT-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1004%3A23124&show-proto-sidebar=1).
2. In [this figma file for person](https://www.figma.com/proto/bWS2orxFECNrG92HfG48BL/LUX-Yale-Design-Walkthrough?page-id=182%3A6364&node-id=1152-10519&viewport=-5411%2C-5010%2C0.36&t=yi4XGHaZfpsKRsqT-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1152%3A10519&show-proto-sidebar=1), the person's relationships appear above the `About` section. In the example [objects page](https://www.figma.com/proto/bWS2orxFECNrG92HfG48BL/LUX-Yale-Design-Walkthrough?page-id=182%3A6364&node-id=803-23404&viewport=-5411%2C-5010%2C0.36&t=yi4XGHaZfpsKRsqT-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=803%3A23404&show-proto-sidebar=1), the `About` section also has to be scrolled to and is not immediately available at the top of the page. Should the `About` section be at the top of the page so that it is the first thing users see on an entity page? 
3. Based on [Amy's comment above](https://github.com/project-lux/lux-frontend/issues/269#issuecomment-2374420034), this is a mistake and the `Give Feedback` button should be above the `Data Sources` component as it is now in the Desktop view. The mobile placement of the button will be reflective of the desktop placement. [Current figma file here](https://www.figma.com/proto/bWS2orxFECNrG92HfG48BL/LUX-Yale-Design-Walkthrough?page-id=182%3A6364&node-id=803-23404&viewport=-5411%2C-5010%2C0.36&t=yi4XGHaZfpsKRsqT-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=803%3A23404&show-proto-sidebar=1) is incorrect.
4. General comment. No action needed.
5. Entity page dropdown menu options should be connected to their child content similar to the results page tab dropdown menu. 
6. Right description will be closed on default as mentioned in [this comment](https://github.com/project-lux/lux-frontend/issues/269#issuecomment-2407707286).

@prowns Please confirm if the statements for 1, 3, 4, 5, and 6 are correct. Please confirm if 2 is still being discussed as I was not sure based on the comments in this issue.

**Comment by kamerynB** [comment]
This issue will act as a meta ticket for further mobile work. Any issues created that pertain to this issue will be given the same priority.

**Comment by roamye** [comment]
UAT 11/6: 
Desktop changes from #270 are to be implemented first.

**Comment by roamye** [comment]
Moved to milestone 01-13 as their are child issues that still need to be worked on.

**Comment by roamye** [comment]
Closing - all issues have been completed.
