### ISSUE TITLE
META: Saved Collections/Bookbag Service (from 1783)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#42]
**Problem Description:**
This is a Meta ticket for a new bookbag/save/export feature in LUX.  

**Expected Behavior/Solution:**
The bookbag/save/export feature in LUX  will allow users to save URL searches/items to their collection from LUX, Library, etc. It will also have all MVP features listed in the requirements spreadsheet below. 

**Requirements:**
https://docs.google.com/spreadsheets/d/1C04s3JUD2WoLgPrOEvRz645GluBWxHwjUFQuGNOOLYs/edit#gid=0 - Sarah

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Requirements - sarah
- [x] user access workflow - Amy
- [x] wire/frame mockup for user access - Mike
- [x] bookbag workflow - Amy 
- [x] wire/frame mockup for bookbag workflow - Mike
- [x] protype
- [ ] testing
- [ ] approval
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] ~Questions~
- ~List of questions for discussions. Answers should be documented within the issue.~

**UAT/LUX Examples:**
- Example endpoints from LUX to use for development and testing, if applicable.

**Dependencies/Blocks:**
- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

**Related links:**
- [Bookbag Workflow](https://yaleedu-my.sharepoint.com/:u:/r/personal/amy_rodriguez_yale_edu/Documents/Backpack%20Workflow.vsdx?d=w0763cdbef9704153b12c0e19ca32cfcd&csf=1&web=1&e=25qCif)
- User Access Workflow: Tab Process 1.3 
- Bookbag Workflow: Bookbag Workflow - AM change (in progress, need to follow up with M.A to see if any of the changes are feasible) 
- 

**Wireframe/Mockup:**
https://www.figma.com/design/3xP5kimL15r2zJ6n3Ufgeq/LUX?node-id=141-649 

interactive link: https://www.figma.com/proto/3xP5kimL15r2zJ6n3Ufgeq/LUX?node-id=141-650&t=sLWeqa1WF0ubwu4b-1&starting-point-node-id=141%3A650

**Comment by roamye** [comment]
I renamed this to be the META ticket since it was being used as a placeholder. 

@miketullo95 I have added two checkboxes for wire frames, one for the user access (complete and checked off) and one for the bookbag collection (in progress). The link to the workflows is in the Related Links section and it includes information on what tab the workflows are located in. 

Wire frames can be worked on for **User Access**. I will update you when wireframes can be started for the Bookbag workflow.

**Comment by prowns** [comment]
@roamye - can we rescope this ticket to Requirements/POW work and bring to UAT since it's underway?  A place to capture docs and designs.

**Comment by roamye** [comment]
@prowns - https://github.com/project-lux/lux-frontend/issues/617

**Comment by roamye** [comment]
UAT 5/8 -Fine to close.
