### ISSUE TITLE
Improve object/works jump META (from 1802)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#43]
**Problem Description:**
Additional work is requested to improve the jump across objects and works.  Can we had a hover or additional information to indicate the kind of data they will find on the corresponding object or work record?   Given the lack of object/works solution in the near future, this would benefit from redesign.

Note that YUAG and YCBA Works records do not indicate the collecting unit. 

Also, the layout is not consistent
![image](https://github.com/project-lux/lux-frontend/assets/160149818/3a879596-ae06-4831-a2c6-c91deac13452)

**Expected Behavior/Solution:**
Users will understand why/when to navigate across object and works records

**Requirements:**
TBD

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- Example endpoints from LUX to use for development and testing, if applicable.

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

**Related links:**

- https://www.bugherd.com/projects/284041/tasks/1724
- https://www.bugherd.com/projects/284041/tasks/881 (tangentially related)
- https://www.bugherd.com/projects/284041/tasks/1995 (tangentially related - creators)
- https://www.bugherd.com/projects/284041/tasks/1846

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by kamerynB** [comment]
@prowns Works/objects Included shows results snippets now. Can this ticket me closed as it is outdated?

cc: @jffcamp @roamye

**Comment by prowns** [comment]
Yes, closing.
