### ISSUE TITLE
Add new metrics captures to SiteImprove (meta) (from 1869)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#51]
**Problem Description:**
In discussions of #1729 and autocomplete, we realized that there are additional events that Site Improve could capture, and concerns raised that analytics were not accurately representing usage. This ticket has been expanded to cover all improvements to SiteImprove tracking. 

**Expected Behavior/Solution:**
Improve the ability to get meaningful data from SiteImprove with additional events and other analytics tracking and reports. 

**Requirements:**
 https://docs.google.com/spreadsheets/d/1VICQvsPW2IJpkOFV20dGoIe5DsiLp-geYW_d3nXtcZk/edit#gid=0

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.
- [x] Consultation with SI - Peter, Jeff, Sarah
- [x] Documentation of Requirements - team
- [x] Decision to manage implementation in the spreadsheet
- [x] https://git.yale.edu/lux-its/lux-web/issues/1994
- [x] ~#120~
- [x] #124 
- [x] Confirm SI is working accurately with single page app
- [x] #77 - Peter
- [x] #78  - Peter 
- [x] #90 - April Sprint
- [x] #91 - TBD
- [x] Track implementation on spreadsheet for each requirement - Amy

**UAT/LUX Examples:**

- UAT in spreadsheet by viewing reports

**Dependencies/Blocks:**
- #77 
- #78 
NOTE: work can proceed without this, but there will be some code updates when this gets deployed

**Related Github Issues:**

**Related links:**
- [Private Teams Chat](https://teams.microsoft.com/l/message/19:GmLeQu1cBR40mfrno-l8lngg7RFCcJs8fvFIw-MJjIM1@thread.tacv2/1695222335858?tenantId=dd8cbebb-2139-4df8-b411-4e3e87abeb5c&groupId=4620eac6-0955-4c69-93e8-b493b21f0df6&parentMessageId=1695222335858&teamName=MarkLogic&channelName=General&createdTime=1695222335858&allowXTenantAccess=false)

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by prowns** [comment]
@roamye and @kamerynB - is this still an active ticket, or can it be closed?

**Comment by kamerynB** [comment]
@prowns All of it's supporting tickets are complete so I would say it can be closed. #91 should be closed as well. I'll let @roamye leave her input though since she was doing a lot of the tracking/checking in SI.

**Comment by roamye** [comment]
#91 had two boxes left to be checked off. Those being to track the simple searches and advanced searches submitted in LUX. 

I checked off the tracking of internal searches as the SI internal searches has been set up already. 
However, the AS searches have not. (Unless we want to look through the advanced search event to see what queries users are creating before hitting the search lux button.) I suggest...

1) closing 91 if we want to use the events to look at AS searches. Or ...
2) creating a ticket for this last requirement and taking it off of #91 to close both 91 and this ticket (51).

**Comment by kamerynB** [comment]
@prowns Definitely an agenda topic. I'll add it to the notes.

cc: @roamye

**Comment by roamye** [comment]
From IT meeting 7/12: 
#91 was OK to close and since there are no outstanding issues left this ticket is also good to close.
