### ISSUE TITLE
Events Page - Meta Ticket for adding more related content to view (from 1884)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#56]
Problem Definition: The events pages are not showing all the available related data that they could be showing using existing HAL links

Expected Behavior: Show all possible relationships on events for improved discovery

BLOCKED by:

- #8 
- [#9 ](https://github.com/project-lux/lux-frontend/issues/9)

Needed

- [x] wireframe
- [x] Review by dev team
- [x] Revisions if needed

Wireframe is too long to screenshot well so can be viewed here: https://nj46vq.axshare.com/?id=g4ubgg&p=entity_-_event_-_oct_23
<img width="594" alt="image" src="https://git.yale.edu/storage/user/2590/files/3812a672-fc0e-4ea1-be5c-

![image](https://github.com/project-lux/lux-frontend/assets/160149818/9040be02-1092-4562-a6eb-3b05b393c0b0)

Related Tickets: 
- [x] https://github.com/project-lux/lux-frontend/issues/6
- [x] https://github.com/project-lux/lux-frontend/issues/7
- [x] https://github.com/project-lux/lux-frontend/issues/8
- [x] https://github.com/project-lux/lux-frontend/issues/4
- [x] https://github.com/project-lux/lux-frontend/issues/9
- [x] https://github.com/project-lux/lux-frontend/issues/57

**Comment by jffcamp** [comment]
@clarkepeterf - requires HAL Link ticket

**Comment by prowns** [comment]
Keeping open until issues are all completed.

**Comment by roamye** [comment]
Front end #8 is closed and previously blocked this ticket. 
All related issues are closed. 

I will remove the blocked label - but I am suggesting propose close as this is the META tix. 

@kamerynB let me know if u agree.

**Comment by kamerynB** [comment]
@roamye Please close 😃

**Comment by roamye** [comment]
closing as meta tix and blocking tix is also closed. (UAT)
