### ISSUE TITLE
Add subject of work to object and work pages (from 1927)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#62]
**Problem:**
Currently, there are relationships where a user can navigate to one entity from another but with no way of connecting the second entity back to the first.   This is a high impact issue, and will go up with the addition of PMC data (photographs of works, but not objects).

**Expected Behavior:**
~Add in the about entity module to Works pages to showcase related Objects.  Accordion should look like the results list for works about on an entity page (Works about list).  Show 5, with show all X results to run search.  Scope is Works only. This label on the referring page will also need to be updated to match the new terminology.~

On Works pages (both visual and textual works), there should be a way of connecting back to the work that it is the subject of. A link will be added to the About section of Works for "Subject Of" where available. This change should also occur on Objects pages where the object shown is a subject of another work. It should always link back to a work.

**Needed:**

- [x] Team/feasibility discussion (11/17/23)
- [x] Mockup - Heather
- [x] Team mockup review - 12/8/23
- [x] HAL link needed https://github.com/project-lux/lux-middletier/issues/28- Peter
- [x] Clarify label of accordion.  It's really: Works About This Work - need something better
- [x] is this issue impacted by https://git.yale.edu/LUX/pipeline/issues/591?  (not necessarily a blocker)

**UAT:**
- [Le Jardin de Daubigny](https://lux.collections.yale.edu/view/text/29b98ec5-b8c9-405e-a83f-03e2eb5a427b) is about [Daubigny's Garden](https://lux.collections.yale.edu/view/text/5ad5d97a-1b16-42c4-ad5e-145b2371643b). Daubigny's Garden should show `Subject of: Le Jardin de Daubigny` in the About section.

- [this text](https://lux-front-tst.collections.yale.edu/view/text/7bbd4203-95ed-4d66-b9e2-a78c23217edb) is about [Alphabet Book South Russian](https://lux-front-tst.collections.yale.edu/view/text/2bc1c5a0-0085-449f-bf60-ca685d72f128). Alphabet Book South Russian should show `Subject of: the text` in the About section.

- https://lux-front-tst.collections.yale.edu/view/text/7ae0fcb3-41c5-400e-be63-337b70536dff

**Dependencies/Blocking:**

- [ ] Blocked by: https://github.com/project-lux/lux-middletier/issues/28
- [x] The above MT issue is blocked by: https://github.com/project-lux/lux-marklogic/issues/74

**Related issues:**
 - https://github.com/project-lux/lux-frontend/issues/29

**Related Bugherd:**
- https://www.bugherd.com/projects/284041/tasks/1792

**Wireframe:**
Mock of work  with Subject Of for https://lux-front-tst.collections.yale.edu/view/text/2bc1c5a0-0085-449f-bf60-ca685d72f128

![image](https://github.com/project-lux/lux-frontend/assets/160149818/5f673c79-2134-40e6-8220-768e380ed569)

![62](https://github.com/project-lux/lux-frontend/assets/98550395/4c9724dd-38e5-4c3f-ab93-a4154b81a52e)

**Comment by kamerynB** [comment]
@kkdavis14 Can you accurately describe what the behavior should be/what the user should see? The examples above are confusing to me.

**Comment by kkdavis14** [comment]
first I do not think this is blocked by the pipeline Set issue. That work would group together a bunch of e.g. textual works into a Set and change the link in About to the Set, not each individual textual work. it's still the same relationship, even if the data type changes

**Comment by kkdavis14** [comment]
handy count (this is from October so slightly outdated):
there are 439210 textual works that are about other textual works.
there are 208 textual works that are about objects.

there are 2387 visual works that are about textual works.
there are 3 visual works that are about objects.

**Comment by miketullo95** [comment]
@prowns added works about in wireframe

**Comment by roamye** [comment]
Approved by UAT 9/12

**Comment by roamye** [comment]
Looks good in PROD. Closing.
