### ISSUE TITLE
Advanced Search improvements (from 1928)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#63]
**Problem Description:**
Meta ticket for Advanced Search Improvements.  This ticket should be promoted to dev board along with all the other related tickets, when prepared. 

**Expected Behavior/Solution:**
TBD

**Requirements:**
https://app.smartsheet.com/sheets/HhQC82P9vXGM5pXj96824Hq6ggH385RW2635G6q1?view=grid

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Related Tickets formed 
- [ ] Requirements approved by Core and Dev Teams
- [ ] Requirements reviewed with Interactions
- [ ] Further tickets added/connected here
- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

**Dependencies/Blocks:**

**Related Github Issues:**
- https://git.yale.edu/lux-its/lux-web/issues/1892
- https://git.yale.edu/lux-its/lux-web/issues/1801
- Note UAT comments on https://git.yale.edu/lux-its/marklogic/issues/1097
- https://www.bugherd.com/projects/284041/tasks/1885

**Related links:**
- https://www.bugherd.com/projects/284041/tasks/1840
- location in [LUX](https://lux-front-tst.collections.yale.edu/view/results/concepts?q=%7B%22influencedByEvent%22%3A%7B%22name%22%3A%22dynasty%22%7D%7D)
- https://www.bugherd.com/projects/284041/tasks/1885
- location in [LUX](https://lux-front-sbx.collections.yale.edu/view/results/objects?q=%7B%22_scope%22%3A%22item%22%2C%22OR%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F4a172143-a50e-4d91-a88b-a9931bceecf1%22%7D%7D%2C%7B%22material%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F4a172143-a50e-4d91-a88b-a9931bceecf1%22%7D%7D%5D%7D&openSearch=false)

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by ar2674** [comment]
Closing as this is similar to #14, all information from this tix has been put into #14
