### ISSUE TITLE
Reg Priority SI Events (from 2046)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#91]
**Problem Description:**
In the spreadsheet requirements #1869, there are high priority events and non high priority events. It was decided that non priority events will have their scope of work on a different ticket. 

event tracking documentation: https://docs.google.com/document/d/1jsH4ckYOW7ykXlKACctZOP1IpxYnGaRIRPGDiuUbGMQ/edit

**Expected Behavior/Solution:**
Use this ticket for the scope of work for the remaining non priority events. 

**Requirements:**
- https://docs.google.com/spreadsheets/d/1VICQvsPW2IJpkOFV20dGoIe5DsiLp-geYW_d3nXtcZk/edit#gid=0

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.
**Event Add**
- [ ] Timeout triggered | cannot be currently tracked. 
Note: this was tested to see whether a timeout triggered would result in an error event but the error events do not capture this.

**Lux System Searches**
- [x] Capture what users enter in simple search - Peter 
- [x] Capture what users enter in advanced search - Peter 

**Review Content**
- [x] Time on site (covered by SI behavior - visit lengths) 
- [x] Show title of LUX page (for 04/29 deployment) 

 _**Events - Already Tracking**_
- [x] Advanced Search bar - opened or collapsed | https://github.com/project-lux/lux-frontend/issues/161
- [x] Advanced Search scope selected from home page | https://github.com/project-lux/lux-frontend/issues/161
- [x] Advanced Search created by user and submitted | https://github.com/project-lux/lux-frontend/issues/161
- [ ] ~Advanced Search edited from within LUX~ This isn't necessarily trackable as users can only perform an advanced search from the results page
- [x] Simple search changed to Advanced | https://github.com/project-lux/lux-frontend/issues/162
- [x] Advanced search changed to Simple | https://github.com/project-lux/lux-frontend/issues/162
- [x] Continue switch to Simple Search Button | https://github.com/project-lux/lux-frontend/issues/162
- [x] Go to Page number changed (pagination on results) | https://github.com/project-lux/lux-frontend/issues/168
- [x] Next or Previous page in Related accordion selected (pagination in Related List accordion) | https://github.com/project-lux/lux-frontend/issues/168
- [x] Exit to feedback from button | 
- [x] ~Simple search edited and resubmitted~ (this cannot be tracked. Although if they submit a search from a results page we can assume they have edited their search. )
- [x] Sort By changed in results view
- [x] Grid View selected in results view
- [x] Tab on entity page selected
- [x] Sort By changed in results view
- [x] Grid View selected in results view
- [x] Tab on entity page selected
- [x] Exits to "view this item on Unit homepage" | https://github.com/project-lux/lux-frontend/issues/167
- [x] Link to "highlight" record on home page is clicked (tracks the selection of the collections on the homepages) | https://github.com/project-lux/lux-frontend/issues/169
- [x] Clicks on links in result cards other than the thumb/title - These are all the RecordLink component #164
- [x] Error message triggered | https://github.com/project-lux/lux-frontend/issues/172
- [x] Clicks on page links
- [x] Jumps to https://lux.collections.yale.edu/content/faq from within LUX | https://github.com/project-lux/lux-frontend/issues/169
- [x] Exit to feedback from footer link | https://github.com/project-lux/lux-frontend/issues/167

_**Understand Demographics**_
- [x] Organization
- [x] Device
- [x] OS
- [x] Browser
- [x] Screen Resolution

_**Understand User Behavior**_
- [x] Path tracking
- [x] Entry and exit pages
- [x] Traffic sources
- [x] Bounce rate by traffic source

_**Review Content**_
- [x] Page views
- [x] Navigaton depth

_**Other**_
~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
- [x] Frontend requirements- add appropriate Event Action per the linked spreadsheet
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- Example endpoints from LUX to use for development and testing, if applicable.

**Dependencies/Blocks:**
-  Dependencies: https://git.yale.edu/lux-its/lux-web/issues/2016 and https://git.yale.edu/lux-its/lux-web/issues/2015
NOTE: not a blocker, but will require some refactoring when those are implemented.

**Related Github Issues:**
- https://git.yale.edu/lux-its/lux-web/issues/1869 (META)

**Related links:**

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by jffcamp** [comment]
@roamye & @kamerynB , I think this is a tracking ticket. Will it be moved back to on deck now?
Amy, we should also take the tickets that were just deployed and move them to the already tracking section. So only the unchecked items remain at the top.

**Comment by roamye** [comment]
Moving this back to deck since there are still some checkboxes unchecked. Others have been implemented in this deployment cycle and are listed below as event-already added.

**Comment by roamye** [comment]
Moving this back to deck since the next checkboxes that need to be complete are for @clarkepeterf (please see LUX System Searches above). 

Peter, would the LUX system searches need to be researched? If so, I can create a research ticket for those and then close out this one. 

@kamerynB the title pages seem to work ok, but they are a couple of things we may want to fix, as some pages still show the "unknown title" for those which come from internal lux.

**Comment by roamye** [comment]
From IT meeting 7/12 - 
This is OK to close as the last two checkboxes are already covered by what has been implemented already.
